name: first-workflow22
on: 
  push:
    branches:
      - mac-main  # Ensure it triggers only on pushes to 'main' branch
jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v
